apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: cicd-tkc
  namespace: from-argocd
spec:
  distribution:
    version: v1.18.5
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu-k8s-custom-policy
    workers:
      count: 1
      class: best-effort-small
      storageClass: tanzu-k8s-custom-policy
